name: Keep Render Backend Awake

on:
  schedule:
    - cron: "*/9 * * * *"  # every 14 minutes

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Ping the Render backend
        run: curl -s https://portfolio-website-backend-o452.onrender.com/api/info/about
